# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('arquivo', models.FileField(upload_to=b'', verbose_name='Arquivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('descricao', models.CharField(help_text='Ex: Dia da marmota', max_length=255, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'ordering': ('dia',),
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('pis', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='PIS/PASEP')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ctps', models.CharField(max_length=255, unique=True, verbose_name='Carteira de trabalho')),
                ('funcao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fun\xe7\xe3o')),
                ('data_admissao', models.DateField(verbose_name='Data de Admiss\xe3o')),
                ('segunda', models.TimeField(default=datetime.time(8, 0), verbose_name='Segunda Feira')),
                ('terca', models.TimeField(default=datetime.time(8, 0), verbose_name='Ter\xe7a Feira')),
                ('quarta', models.TimeField(default=datetime.time(8, 0), verbose_name='Quarta Feira')),
                ('quinta', models.TimeField(default=datetime.time(8, 0), verbose_name='Quinta Feira')),
                ('sexta', models.TimeField(default=datetime.time(8, 0), verbose_name='Sexta Feira')),
                ('sabado', models.TimeField(default=datetime.time(0, 0), verbose_name='S\xe1bado')),
                ('domingo', models.TimeField(default=datetime.time(0, 0), verbose_name='Domingo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='ponto.Departamento', verbose_name='Departamento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acesso')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Funcion\xe1rio',
                'verbose_name_plural': 'Funcion\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Dia \xfatil'), (1, 'Folga ou feriado'), (2, 'Falta'), (3, 'Falta abonada'), (4, 'Consumo de hora extra')], default=0, verbose_name='Tipo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observa\xe7\xf5es')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='ponto.Funcionario', verbose_name='Funcion\xe1rio')),
            ],
            options={
                'ordering': ('-dia', 'funcionario__nome'),
                'verbose_name': 'Registro de ponto',
                'verbose_name_plural': 'Registros de ponto',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data da cria\xe7\xe3o')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data da atualiza\xe7\xe3o')),
                ('deletado', models.BooleanField(default=False, verbose_name='deletado')),
                ('horario', models.DateTimeField(verbose_name='Hor\xe1rio')),
                ('registro_manual', models.BooleanField(default=False, verbose_name='Registrofeito manualmente')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='ponto.Ponto', verbose_name='Ponto')),
            ],
            options={
                'ordering': ('horario',),
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.AddField(
            model_name='anexo',
            name='ponto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ponto.Ponto', verbose_name='Ponto'),
        ),
        migrations.AlterUniqueTogether(
            name='ponto',
            unique_together=set([('funcionario', 'dia')]),
        ),
    ]
